# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_verificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_reset_code',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.ManyToManyField(blank=True, to='auth_api.Team'),
        ),
    ]
