# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_auto_20171217_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='team',
        ),

        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.ManyToManyField(blank=True, through='auth_api.InvitationLink', to='auth_api.Team'),
        ),
    ]
